### ISSUE TITLE
Support for T11

### ISSUE THREAD

**Issue by dmitriim** [catalyst/totara-mod-ojt#13]
While testing the plugin in T11 I got the following errors/warnings:

`The function ojt_print_recent_activity have being deprected since totara 11
line 234 of /blocks/recent_activity/block_recent_activity.php: call to debugging()
line 74 of /blocks/recent_activity/block_recent_activity.php: call to block_recent_activity->get_modules_recent_activity()
line 288 of /blocks/moodleblock.class.php: call to block_recent_activity->get_content()
line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1180 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1235 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 354 of /lib/blocklib.php: call to block_manager->ensure_content_created()
line 38 of /theme/alh/layout/default.php: call to block_manager->region_has_content()
line 844 of /lib/outputrenderers.php: call to include()
line 774 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 252 of /course/view.php: call to core_renderer->header()`

**Comment by euven** [comment]
Hi @dmitriim 

I did remove this function already - see https://github.com/catalyst/totara-mod-ojt/commit/b9ec459003ce3cd48a4911fc528dd374d8b479b2

Could you test on T11 with the master branch and let me know if you encounter any issues?

I'll leave this issue open for now ;)

Thanks!
Eugene.

**Comment by dmitriim** [comment]
Hi @bynare ! Sorry was using v10 branch. I was confused by WIKI https://github.com/catalyst/totara-mod-ojt/wiki Was thinking a branch should match a version.  Maybe we should remove this section from the wiki?

![image](https://user-images.githubusercontent.com/4626431/40026338-51abf242-5818-11e8-9162-b37d51ad0004.png)

**Comment by euven** [comment]
I agree @dmitriim  - removed that bit, as it can become stale too easily ;)

**Comment by euven** [comment]
@dmitriim can you confirm that everything works as expected on Totara 11? If it does, I'll create a new branch for Totara 11.

**Comment by dmitriim** [comment]
@bynare looks like it works well.
