### ISSUE TITLE
OJT plugin doesn't work in Totara 12

### ISSUE THREAD

**Issue by danmarsden** [catalyst/totara-mod-ojt#16]
Throws a bunch of deprecated warnings and then triggers an exception on
/mod/ojt/rb_sources/rb_source_ojt_completion.php
Exception - Property addeduserjoins does not exist
line 191 of /totara/reportbuilder/classes/rb_base_source.php: call to rb_base_source->finalise_bc_trait_instance()
line 81 of /mod/ojt/rb_sources/rb_source_ojt_completion.php: call to rb_base_source->__construct()

**Comment by rahuldossier** [comment]
How did you fixed this issue

**Comment by danmarsden** [comment]
probably rolled up in a bunch of changes we made at the time.

Just make sure you are using the latest version of the plugin for T12 and you should be fine.
