### ISSUE TITLE
Checkbox spinning in IE

### ISSUE THREAD

**Issue by oliver-jk-redding** [catalyst/totara-mod-ojt#20]
When you tick then untick the checkbox in IE, the unticked checkbox begins to spin. It seems that clicking the checkbox causes a loading icon to appear for a split second, presumably while some backend processing is going on. The loading icon is a circle of spinning dots using two classes: "fa-spinner" (a circle of dots) and "fa-pulse" (a class that causes the other icon to spin). When you untick the checkbox, for some reason, in IE, the "fa-pulse" class doesn't get removed once the unticked checkbox icon is loaded. This results in a spinning unticked checkbox.

**Comment by danmarsden** [comment]
closing as wont' fix - IE support is no longer supported by Microsoft either. - thanks!
