### ISSUE TITLE
Inability to archive completions

### ISSUE THREAD

**Issue by sergeyandrogogic** [catalyst/totara-mod-ojt#29]
When a certification window opens a course, its activities are reset; however the OJT activity module is NOT reset and any exisitng topic completions, comment and uploads are kept intact.

**Comment by sergeyandrogogic** [comment]
This patch (according to our UAT) solves the issue. Hopefully it gets integrated in the core code: this issue is a roadblock for a fair few of our clients.
[ojt_patch.txt](https://github.com/catalyst/totara-mod-ojt/files/5969145/ojt_patch.txt)

**Comment by sergeyandrogogic** [comment]
Here's an additional patch to take care of comments as well, should they ever be added to the activity.
Does anybody even read this at all? This is a very important issue.
[comments_diff.txt](https://github.com/catalyst/totara-mod-ojt/files/6168500/comments_diff.txt)

**Comment by danmarsden** [comment]
Thanks Sergey! We do read these but just like you we're crazy busy these days. 

I'm not sure we have someone specific leading maintenance on ojt but I'll see if we can drop this in the queue to cone back to sometime.

All the best!

**Comment by danmarsden** [comment]
FYI - I've created an internal ticket for this, so hopefully we'll get someone assigned to look at it soon.
