### ISSUE TITLE
Exception - Class 'mod_ojt\rb\content\html_writer' not found

### ISSUE THREAD

**Issue by AndyNicolle** [catalyst/totara-mod-ojt#35]
When trying to access the content tab on an OJT report the attached error is produced with developer level debugging switched on.
![OJT_error](https://user-images.githubusercontent.com/74614479/123411156-0d579e00-d5a8-11eb-8ca0-3e6403e2ded4.jpg)

**Comment by DrCuriosity** [comment]
Hi @AndyNicolle,

Could you please pull a fresh copy of the OJT plugin, and verify that the error is resolved for you? Thanks!

**Comment by alexmorrisnz** [comment]
This was fixed in David's PR, closing.
