### ISSUE TITLE
Exception on using user related content option on ojt_topic_item_completion report

### ISSUE THREAD

**Issue by fergus-catalyst** [catalyst/totara-mod-ojt#38]
The content option references no longer existing tables and causes a crash on page load. 

Instructions:
Create a report of the type OJT Topic Item.
Edit the report on the Content option tab.
Add a "user" related content option. 
Save and click view report. 

I have created a pull request to fix this: #37

**Comment by alexmorrisnz** [comment]
PR was merged, this has been resolved.
