### ISSUE TITLE
Totara 9 - Witnessed not working

### ISSUE THREAD

**Issue by mlstotara** [catalyst/totara-mod-ojt#9]
The "Witnessed" option does not work on Totara 9. It just shows an empty box.
![screenshot_20171115_101907](https://user-images.githubusercontent.com/33671458/32805485-717d9156-c9ee-11e7-98cb-109af7fa1379.png)

**Comment by danmarsden** [comment]
I'm closing this as "won't fix" as it relates to totara 9, but please let us know if you have any issues with newer Totara versions - thanks!
